export const PRODUCTS = [
    {
        id: 1,
        category: 1,
        name: 'Pan Baguette',
        description: 'Rico pan baguette',
        weight: '1/2 kg',
        price: 10,
        image:require("../../assets/images/baguette.png"),
    },
    {
        id: 2,
        category: 1,
        name: 'Pan de Queso',
        description: 'Rico Pan de queso',
        weight: '1/4 kg',
        price: 15,
        image:require("../../assets/images/queso.png"),
    },
    {
        id: 3,
        category: 2,
        name: 'Pan Integral',
        description: '',
        weight: '1/3 kg',
        price: 20,
        image:require("../../assets/images/integral.png"),
    },
    {
        id: 4,
        category: 2,
        name: 'Pan Integral con semillas',
        description: '',
        weight: '1/3 kg',
        price: 25,
        image:require("../../assets/images/integra_semilla.png"),
    },
    {
        id: 5,
        category: 3,
        name: 'Pan de centeno',
        description: 'Rico Pan de centeno',
        weight: '1/4 kg',
        price: 15,
        image:require("../../assets/images/centeno.png"),
    },
    {
        id: 7,
        category: 4,
        name: 'Pan de millo',
        description: '',
        weight: '1/4 kg',
        price: 15,
        image:require("../../assets/images/maiz.png"),
    },
    {
        id: 8,
        category: 4,
        name: 'Bizcochos',
        description: 'Bizcochos',
        weight: '1/3 kg',
        price: 20,
        image:require("../../assets/images/bizcochos.png"),
    },
]